name: 'Setup action 1'
description: 'Reusable setup steps for action 1'
inputs:
  input1:
    description: 'Input for action 1'
    required: true
    default: 'default1'
runs:
  using: "composite"
  steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Read version from version.json
      id: read_version
      run: |
        echo "::set-output name=version::$(jq -r .version ./src/Atmosphere/version.json)"

    - name: Set version as environment variable
      run: echo "VERSION=${{ steps.read_version.outputs.version }}" >> $GITHUB_ENV
