name: 'Docker Hub Common Setup'
description: 'Reusable setup steps for gihub actions that push to docker hub'

inputs:

  docker_hub_username:
    description: 'Docker Hub Username'
    required: true

  docker_hub_access_token:
    description: 'Docker Hub Access Token'
    required: true

  docker_image:
    description: 'Docker Image Name'
    required: true

  channel_tag:
    description: 'Docker channel tag'
    required: true

  version_tag:
    description: 'Docker version tag'
    required: true

  docker_file_path:
    description: 'Docker file path'
    required: true

  source_directory:
    description: 'Source files directory'
    required: true
    
runs:

  using: "composite"

  steps:

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ inputs.docker_hub_username }}
        password: ${{ inputs.docker_hub_access_token }}

    - name: Build the Docker image
      shell: bash
      run: docker build --tag ${{ inputs.docker_image }}:${{ inputs.channel_tag }} --tag ${{ inputs.docker_image }}:${{ inputs.version_tag }} --file ${{ inputs.docker_file_path }} ${{ inputs.source_directory }} 

    - name: Push the Docker image Version
      shell: bash
      run: docker push ${{ inputs.docker_image }}:${{ inputs.version_tag }} 

    - name: Push the Docker image Channel
      shell: bash
      run: docker push ${{ inputs.docker_image }}:${{ inputs.channel_tag }}