name: 'Docker Hub Common Setup'
description: 'Reusable setup steps for gihub actions that push to docker hub'

inputs:

  docker_hub_username:
    description: 'Docker Hub Username'
    required: true

  docker_hub_access_token:
    description: 'Docker Hub Access Token'
    required: true

runs:

  using: "composite"

  steps:
  
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ inputs.docker_hub_username }}
        password: ${{ inputs.docker_hub_access_token }}
