name: Docker Hub Stable

on:
  push:
    branches:
      - release/stable

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Get current project version
      uses: ./.github/actions/get-version
      with:
        version_file_path: ./src/Atmosphere/version.json
    
    - name: Verify version
      run: |
        if [[ "${{ env.VERSION }}" =~ ^[0-9\.]+$ ]]; then
          echo "Version is valid"
        else
          echo "Invalid version"
          exit 1
        fi

    - name: Login to Docker Hub
      uses: ./.github/actions/docker-hub
      with:
        docker_hub_username: ${{ secrets.DOCKER_HUB_USERNAME }}
        docker_hub_access_token: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    
    - name: Docker Build
      uses: ./.github/actions/docker-build
      with:
        docker_image: ${{ vars.DOCKER_IMAGE }}
        channel_tag: latest
        version_tag: ${{ env.VERSION }}
        docker_file_path: ./docker/Dockerfile
        source_directory: ./src
    
    - name: Docker Push
      uses: ./.github/actions/docker-push
      with:
        docker_image: ${{ vars.DOCKER_IMAGE }}
        channel_tag: latest
        version_tag: ${{ env.VERSION }}
    

