name: 'Docker Hub Common Setup'
description: 'Reusable setup steps for gihub actions that push to docker hub'
runs:
  using: "composite"
  steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Read version from version.json
      id: read_version
      run: |
        echo "::set-output name=version::$(jq -r .version ./src/Atmosphere/version.json)"

    - name: Set version as environment variable
      run: echo "VERSION=${{ steps.read_version.outputs.version }}" >> $GITHUB_ENV
